---
- name: Check parameter pkg_name.
  fail:
    msg: "pkg_name parameter is not defined. Confirm pkg_name parameter."
  when:
    - parameter.pkg_name is not defined

- name: Check parameter action. ({{ parameter.pkg_name }})
  fail:
    msg: "action parameter is not defined. Confirm action parameter."
  when:
    - parameter.action is not defined

- name: Check parameter action. ({{ parameter.pkg_name }})
  fail:
    msg: "Invalid value is set for the action parameter({{ parameter.action }}). Confirm action parameter."
  when:
    - parameter.action != 'present'
    - parameter.action != 'absent'

