---
- name: Check parameter group_name.
  fail:
    msg: "group_name parameter is not defined. Confirm group_name parameter."
  when:
    - parameter.group_name is not defined

- name: Check parameter action. ({{ parameter.group_name }})
  fail:
    msg: "action parameter is not defined. Confirm action parameter."
  when:
    - parameter.action is not defined

- name: Check parameter action. ({{ parameter.group_name }})
  fail:
    msg: "Invalid value is set for the action parameter({{ parameter.action }}). Confirm action parameter."
  when:
    - parameter.action != 'present'
    - parameter.action != 'absent'

