---
- name: Write file. ({{ parameter.path }})
  template:
    src: flat_template
    dest: "{{ parameter.path }}"
  register: template_result
  when: parameter.file is undefined or parameter.file is none or parameter.file == ''

- name: Copy file. ({{ parameter.file }})
  copy:
    src: "{{ parameter.file }}"
    dest: "{{ parameter.path }}"
  register: copy_result
  when:
  - parameter.file is defined
  - parameter.file is not none
  - parameter.file != ''

- name: Restart sshd.
  systemd:
    state: restarted
    name: sshd
  when: template_result.changed or copy_result.changed
