---
- name: Write file.({{ parameter.path }})
  block:
    - name: Command SELINUX disabled
      command: 'grubby --update-kernel ALL --args selinux=0'
      with_dict:
        "{{ parameter.properties }}"
      when:
        - parameter.path == '/etc/selinux/config'
        - item.key == 'SELINUX'
        - item.value == 'disabled'

    - name: Command SELINUX other
      command: 'grubby --update-kernel ALL --args selinux=1'
      with_dict:
        "{{ parameter.properties }}"
      when:
        - parameter.path == '/etc/selinux/config'
        - item.key == 'SELINUX'
        - item.value != 'disabled'

    - name: Write file.({{ parameter.path }})
      lineinfile:
        path: "{{ parameter.path }}"
        regexp: '^\s*{{ item.key }}\s*=.*'
        line: '{{ item.key }}={{ item.value }}'
      register: lineinfile_result
      with_dict:
        "{{ parameter.properties }}"
  when: parameter.file is undefined or parameter.file is none or parameter.file == ''

- name: Copy file. ({{ parameter.file }})
  copy:
    src: "{{ parameter.file }}"
    dest: "{{ parameter.path }}"
  register: copy_result
  when:
  - parameter.file is defined
  - parameter.file is not none
  - parameter.file != ''

- name: Reboot OS.
  reboot:
  when: lineinfile_result.changed or copy_result.changed

