---
- name: Write file. {{ gathering_rolepath }}/vars/{{ inventory_hostname }}/vars/gathering_definition.yml
  lineinfile:
    path: "{{ gathering_rolepath }}/vars/{{ inventory_hostname }}/vars/gathering_definition.yml"
    line: "  - ls -ld --time-style=long-iso {{ parameter }}"
    mode: '0644'
  delegate_to: localhost
  become: no
  changed_when: False
