---
- name: Write file.({{ parameter.path }})
  lineinfile:
    path: "{{ parameter.path }}"
    regexp: '^\s*{{ item.key }}\s*=.*'
    line: '{{ item.key }}={{ item.value }}'
  with_dict:
    "{{ parameter.properties }}"
  when: parameter.file is undefined or parameter.file is none or parameter.file == ''

- name: Copy file. ({{ parameter.file }})
  copy:
    src: "{{ parameter.file }}"
    dest: "{{ parameter.path }}"
  when:
  - parameter.file is defined
  - parameter.file is not none
  - parameter.file != ''